version: '3.9'

services:
  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tekber
      - POSTGRES_PASSWORD=tekber
      - POSTGRES_DB=tekber